spring.application.name=event-service
server.port=8083

spring.data.mongodb.uri=mongodb://localhost:27017/rihla_events_db

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

rihla.app.jwtSecret=${JWT_SECRET:rihla-super-secret-key-32-chars-min-2026!!}
