spring.application.name=recommendation-service
server.port=8091

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true


# keep same style as your other services
rihla.app.jwtSecret=${JWT_SECRET:rihla-super-secret-key-32-chars-min-2026!!}
