spring.application.name=itinerary-service
server.port=8093

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true


ai.api.url=https://api.groq.com/openai/v1/chat/completions
ai.api.key=${GROQ_API_KEY:}
ai.model=llama-3.3-70b-versatile

# Maps (free)
spring.data.mongodb.uri=mongodb://localhost:27017/rihla_itinerary

osm.nominatim.baseUrl=https://nominatim.openstreetmap.org
osm.userAgent=RIHLA-PFE-Itinerary/1.0 (contact: natso)

osrm.baseUrl=http://router.project-osrm.org
rihla.app.jwtSecret=${JWT_SECRET:rihla-super-secret-key-32-chars-min-2026!!}
